const getStyles = (theme) => {
    const isDarkMode = theme === 'dark';

    const colors = {
        dark: {
            background: '#121212',
            text: '#E0E0E0',
            primary: '#BB86FC',
            secondary: '#03DAC6',
            surface: '#1E1E1E',
            header: '#1F1F1F',
            input: '#2C2C2C',
            input_text: '#E0E0E0',
            button_text: '#121212',
            border: '#3A3A3A',
            placeholder: '#6A6A6A',
            error: '#CF6679',
            history_overlay: 'rgba(0, 0, 0, 0.7)',
            history_bg: '#2A2A2A',
            result_bg: '#2C2C2C',
            switch_bg: '#333',
            switch_thumb: '#BBB'
        },
        light: {
            background: '#F5F5F5',
            text: '#212121',
            primary: '#6200EE',
            secondary: '#03DAC6',
            surface: '#FFFFFF',
            header: '#FFFFFF',
            input: '#E0E0E0',
            input_text: '#212121',
            button_text: '#FFFFFF',
            border: '#BDBDBD',
            placeholder: '#757575',
            error: '#B00020',
            history_overlay: 'rgba(0, 0, 0, 0.5)',
            history_bg: '#FAFAFA',
            result_bg: '#EEEEEE',
            switch_bg: '#BDBDBD',
            switch_thumb: '#f5f5f5'
        }
    };

    const C = isDarkMode ? colors.dark : colors.light;

    return {
        safeArea: {
            flex: 1,
            backgroundColor: C.background,
            color: C.text,
        },
        container: {
            padding: '20px',
            backgroundColor: C.surface,
            borderRadius: '8px',
            margin: '20px',
            boxShadow: isDarkMode ? '0 4px 8px rgba(0,0,0,0.25)' : '0 4px 8px rgba(0,0,0,0.1)',
        },
        header: {
            display: 'flex',
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            padding: '15px 20px',
            backgroundColor: C.header,
            borderBottom: `1px solid ${C.border}`,
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            zIndex: 1000,
            height: '60px',
        },
        headerLeft: {
            display: 'flex',
            alignItems: 'center',
        },
        headerRight: {
            display: 'flex',
            alignItems: 'center',
        },
        headerTitle: {
            fontSize: '20px',
            fontWeight: 'bold',
            color: C.text,
            marginLeft: '15px',
        },
        title: {
            fontSize: '22px',
            fontWeight: 'bold',
            marginBottom: '20px',
            color: C.text,
            textAlign: 'center',
        },
        inputGroup: {
            marginBottom: '15px',
        },
        label: {
            display: 'block',
            marginBottom: '8px',
            color: C.text,
            fontSize: '14px',
        },
        input: {
            width: '100%',
            padding: '12px',
            border: `1px solid ${C.border}`,
            borderRadius: '4px',
            backgroundColor: C.input,
            color: C.input_text,
            fontSize: '16px',
            boxSizing: 'border-box',
        },
        button: {
            width: '100%',
            padding: '15px',
            border: 'none',
            borderRadius: '4px',
            backgroundColor: C.primary,
            color: C.button_text,
            fontSize: '16px',
            fontWeight: 'bold',
            cursor: 'pointer',
            marginTop: '10px',
        },
        resultContainer: {
            marginTop: '20px',
            padding: '15px',
            backgroundColor: C.result_bg,
            borderRadius: '8px',
        },
        resultTitle: {
            fontSize: '18px',
            fontWeight: 'bold',
            color: C.primary,
            marginBottom: '10px',
        },
        resultText: {
            fontSize: '16px',
            fontWeight: 'bold',
            color: C.text,
        },
        authButton: {
            padding: '10px 15px',
            backgroundColor: 'transparent',
            color: C.text,
            border: `1px solid ${C.border}`,
            borderRadius: '4px',
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            fontSize: '14px',
        },
        authContainer: {
            display: 'flex',
            alignItems: 'center',
            position: 'relative',
        },
        userEmail: {
            marginRight: '10px',
            fontSize: '14px',
            color: C.text,
        },
        menuButton: {
            background: 'none',
            border: 'none',
            cursor: 'pointer',
            padding: '5px',
        },
        menuIcon: {
            width: '24px',
            height: '24px',
            fill: C.text,
        },
        sideMenu: {
            position: 'fixed',
            top: 0,
            left: '-300px',
            width: '300px',
            height: '100%',
            backgroundColor: C.surface,
            boxShadow: '2px 0 5px rgba(0,0,0,0.5)',
            transition: 'left 0.3s ease',
            zIndex: 1001,
            display: 'flex',
            flexDirection: 'column',
        },
        sideMenuHeader: {
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            padding: '15px',
            borderBottom: `1px solid ${C.border}`,
        },
        sideMenuTitle: {
            fontSize: '18px',
            color: C.text,
            margin: 0,
        },
        menuItemContainer: {
            display: 'flex',
            alignItems: 'center',
            borderBottom: `1px solid ${C.border}`,
        },
        menuItemButton: {
            flex: 1,
            padding: '15px',
            background: 'none',
            border: 'none',
            textAlign: 'left',
            color: C.text,
            cursor: 'pointer',
            fontSize: '16px',
        },
        homepageButton: {
            padding: '15px',
            background: 'none',
            border: 'none',
            borderLeft: `1px solid ${C.border}`,
            cursor: 'pointer',
        },
        menuItemActive: {
            backgroundColor: isDarkMode ? 'rgba(187, 134, 252, 0.1)' : 'rgba(98, 0, 238, 0.08)',
        },
        overlay: {
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            backgroundColor: 'rgba(0, 0, 0, 0.5)',
            zIndex: 1000,
        },
        historyButton: {
            padding: '10px 15px',
            backgroundColor: C.primary,
            color: C.button_text,
            border: 'none',
            borderRadius: '4px',
            cursor: 'pointer',
            marginRight: '15px',
        },
        historyOverlay: {
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            backgroundColor: C.history_overlay,
            zIndex: 1002,
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
        },
        historyContainer: {
            backgroundColor: C.history_bg,
            padding: '25px',
            borderRadius: '8px',
            width: '90%',
            maxWidth: '600px',
            maxHeight: '80vh',
            overflowY: 'auto',
            position: 'relative',
            border: `1px solid ${C.border}`
        },
        historyTitle: {
            color: C.text,
            borderBottom: `1px solid ${C.border}`,
            paddingBottom: '15px',
            marginBottom: '15px',
        },
        historyList: {
            listStyle: 'none',
            padding: 0,
        },
        historyItem: {
            backgroundColor: C.surface,
            padding: '15px',
            borderRadius: '6px',
            marginBottom: '10px',
            cursor: 'pointer',
            border: `1px solid ${C.border}`,
        },
        historyItemTitle: {
            fontWeight: 'bold',
            color: C.primary,
        },
        historyItemDate: {
            fontSize: '0.8em',
            color: C.placeholder,
            marginTop: '5px',
        },
        closeButton: {
            position: 'absolute',
            top: '15px',
            right: '15px',
            background: 'none',
            border: 'none',
            cursor: 'pointer',
            color: C.text,
            fontSize: '24px',
        },
        googleIcon: {
            width: '18px',
            height: '18px',
            marginRight: '10px',
            fill: 'currentColor'
        },
        authIncentiveContainer: {
            padding: '20px',
            borderTop: `1px solid ${C.border}`,
            marginTop: 'auto',
        },
        authIncentiveText: {
            color: C.placeholder,
            fontSize: '14px',
            marginBottom: '15px',
        },
        signInButton: {
            width: '100%',
            padding: '12px',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
        },
        switchContainer: {
            display: 'flex',
            alignItems: 'center',
            marginBottom: '15px',
        },
        switchLabel: {
            marginRight: '10px',
            color: C.text,
        },
        switch: {
            position: 'relative',
            display: 'inline-block',
            width: '44px',
            height: '24px',
        },
        switchInput: {
            opacity: 0,
            width: 0,
            height: 0,
        },
        slider: {
            position: 'absolute',
            cursor: 'pointer',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            backgroundColor: C.switch_bg,
            transition: '.4s',
            borderRadius: '34px',
        },
        sliderBefore: {
            position: 'absolute',
            content: '''',
            height: '16px',
            width: '16px',
            left: '4px',
            bottom: '4px',
            backgroundColor: C.switch_thumb,
            transition: '.4s',
            borderRadius: '50%',
        },
    };
}; 

export default getStyles;